name: 'Slack notification'
description: 'Notify slack'

inputs:
  region:
    required: false
    default: 'kor'
  env:
    required: false
    default: 'dev'
  status:
    required: false
    default: 'failure'
  previewName:
    required: false
    default: ''
  domain:
    required: false
    default: 'co.kr'

runs:
  using: 'composite'

  steps:
    - name: Send slack
      shell: bash
      run: |
        echo 'hello'
