name: 'Slack notification'
description: 'Notify slack'

inputs:
  region:
    required: false
    default: 'kor'
  env:
    required: false
    default: 'dev'
  status:
    required: false
    default: 'failure'
  previewName:
    required: false
    default: ''
  domain:
    required: false
    default: 'co.kr'

runs:
  using: 'composite'

  steps:
    - name: Send slack
      shell: bash
      run: |
        # TODO: 슬랙 알림 보내는 템플릿 커스텀 액션 만들기.
        # inputs으로 메시지, 상태만 받는 일관성있는 템플릿 만들기
        if [ "${GITHUB_WORKFLOW}" = "test-every-push" ]; then
          MSG="{ \"text\":\">:no_entry: workflow (<https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}|${GITHUB_WORKFLOW}>) in <https://github.com/${GITHUB_REPOSITORY}|${GITHUB_REPOSITORY}>\n><https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}/checks|${GITHUB_JOB}> job failed, branch=\`${GITHUB_REF#refs/heads/}\`\"}"
        fi

        if [ "${GITHUB_WORKFLOW}" = "deploy" ]; then
          if [ "${{ inputs.env }}" = "preview" ]; then
            SUB_DOMAIN=preview

            if [ "${{ inputs.previewName }}" != "" ]; then
              SUB_DOMAIN=preview-${{ inputs.previewName}}
            fi

            URL=${SUB_DOMAIN}.kakaowebtoonsvc.io
          elif [ "${{ inputs.env }}" = "dev" ]; then
            URL=dev.kakaowebtoon.${{ inputs.domain }}
          elif [ "${{ inputs.env }}" = "sandbox" ]; then
            URL=sandbox.kakaowebtoon.${{ inputs.domain }}
          else
            URL=kakaowebtoon.${{ inputs.domain }}
          fi

          if [ "${{ inputs.status }}" = "success" ]; then
            MSG="{ \"text\":\">:white_check_mark: _${{ inputs.region }}_ ${{ inputs.env }} deploy *completed*\n>branch=\`${GITHUB_REF#refs/heads/}\`\n>${URL}\"}"
          else
            MSG="{ \"text\":\">:no_entry: _${{ inputs.region }}_ ${{ inputs.env }} <https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}/checks|deploy> *failed*\n>branch=\`${GITHUB_REF#refs/heads/}\`\"}"
          fi
        fi

        echo region ${{ inputs.region}}
        echo env ${{ inputs.env}}
        echo sha ${GITHUB_SHA}
        echo refs ${GITHUB_REF#refs/heads/}
        echo repo ${GITHUB_REPOSITORY}
        echo msg ${MSG}
        curl -X POST -H 'Content-type: application/json' --data "${MSG}" https://hooks.slack.com/services/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
