name: auto-weekday-deploy

on: push

jobs:
  auto-weekday-deploy:
    name: 'Auto Build & Deploy'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - region: kor
            s3Path: s3://kakaowebtoon-web-dev/kor
            domain: co.krㅇㅇ

    steps:
      - uses: actions/checkout@v2

      - name: sdafadsfasdf
        id: get
        run: |
          echo "::set-output name=cancel::$(echo truea)"

      - name: Send slack if completed
        if: ${{ success() && steps.get.outputs.cancel != 'true' }}
        uses: ./.github/actions/slack-notify
        with:
          region: ${{ matrix.region }}
          env: dev
          status: success
          domain: ${{ matrix.domain }}

      - name: Send slack if completed
        if: ${{ failure() && steps.get.outputs.cancel != 'true' }}
        uses: ./.github/actions/slack-notify
        with:
          region: ${{ matrix.region }}
          env: dev
          status: success
          domain: ${{ matrix.domain }}
